name: ImageFactory
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pillow=11.1.0
  - pip=25.0
  - setuptools
  - wheel
  - pip:
      - PyQt6==6.8.1
      - PyQt6-Qt6==6.8.2
      - PyQt6-sip==13.10.0